Darphiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from community import views
import notifications.urls
from django.contrib.sitemaps.views import sitemap
from community.sitemaps import QuestionSitemap

sitemaps = {
'questions': QuestionSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('cbt/', include('cbt.urls')),
    path('verify/', include('OTP.urls')),
    path('inbox/notifications/', include( notifications.urls, namespace='notifications')),
  #  path("paystack/", include(('paystack.frameworks.django.urls','paystack' ), namespace='paystack')),
    #REST API
    path('api/accounts/', include('accounts.api.urls', 'accounts')),
    path('api/community/', include('community.api.urls', 'community')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]
urlpatterns= urlpatterns + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

OTP/urls.py
from django.urls import path
from .views import send_otp

urlpatterns = [
    path('send_otp/', send_otp, name='otp')
]

cbt/models.py
import re
import json
import csv
import datetime
from django.db import models


from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import MaxValueValidator, validate_comma_separated_integer_list
from django.utils.timezone import now
from django.conf import settings
from django.utils.translation import ugettext as _

from model_utils.managers import InheritanceManager
from django.db.models.signals import pre_save, post_save
import io
from .signals import csv_uploaded
from .validators import csv_file_validator
from django.contrib.auth.models import User
from django.contrib import messages





class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category


class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"),
        max_length=250, blank=True,
        unique=True, null=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


class Quiz(models.Model):

    title = models.CharField(
        verbose_name=_("Title"),
        max_length=60, blank=False)

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True, help_text=_("a description of the quiz"))

    url = models.SlugField(
        max_length=60, blank=False,
        help_text=_("a user friendly url"),
        verbose_name=_("user friendly url"))

    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"), on_delete=models.CASCADE)

    random_order = models.BooleanField(
        blank=False, default=False,
        verbose_name=_("Random Order"),
        help_text=_("Display the questions in "
                    "a random order or as they "
                    "are set?"))

    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=_("Correct answer is NOT shown after question."
                    " Answers displayed at the end."),
        verbose_name=_("Answers at end"))

    exam_paper = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, the result of each"
                    " attempt by a user will be"
                    " stored. Necessary for marking."),
        verbose_name=_("Exam Paper"))

    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, only one attempt by"
                    " a user will be permitted."
                    " Non users cannot sit this exam."),
        verbose_name=_("Single Attempt"))

    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        verbose_name=_("Pass Mark"),
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)])

    success_text = models.TextField(
        blank=True, help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"))

    fail_text = models.TextField(
        verbose_name=_("Fail Text"),
        blank=True, help_text=_("Displayed if user fails."))

    premium = models.BooleanField(
        blank=True, default=False)
    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed"
                    " in the quiz list and can only be"
                    " taken by users who can edit"
                    " quizzes."))

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        self.url = re.sub('\s+', '-', self.url).lower()

        self.url = ''.join(letter for letter in self.url if
                           letter.isalnum() or letter == '-')

        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"


# progress manager
class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user,
                                   score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Progress is used to track an individual signed in users score on different
    quiz's and categories
    Data stored in csv using the format:
        category, score, possible, category, score, possible, ...
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)

    score = models.CharField(validators=[validate_comma_separated_integer_list], max_length=1024,
                                              verbose_name=_("Score"))

    correct_answer = models.CharField(max_length=10, verbose_name=_('Correct Answers'))

    wrong_answer = models.CharField(max_length=10, verbose_name=_('Wrong Answers'))

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    @property
    def list_all_cat_scores(self):
        """
        Returns a dict in which the key is the category name and the item is
        a list of three integers.
        The first is the number of questions correct,
        the second is the possible best score,
        the third is the percentage correct.
        The dict will have one key for every category that you have defined
        """
        score_before = self.score
        output = {}

        for cat in Category.objects.all():
            to_find = re.escape(cat.category) + r",(\d+),(\d+),"
            #  group 1 is score, group 2 is highest possible

            match = re.search(to_find, self.score, re.IGNORECASE)

            if match:
                score = int(match.group(1))
                possible = int(match.group(2))

                try:
                    percent = float( ((float(score) / float(possible))
                                        * 5.0))
                except:
                    percent = 0

                output[cat.category] = [score, possible, percent]

            else:  # if category has not been added yet, add it.
                self.score += cat.category + ",0,0,"
                output[cat.category] = [0, 0]

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        """
        Pass in question object, amount to increase score
        and max possible.
        Does not return anything.
        """
        category_test = Category.objects.filter(category=question.category)\
                                        .exists()

        if any([item is False for item in [category_test,
                                           score_to_add,
                                           possible_to_add,
                                           isinstance(score_to_add, int),
                                           isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.category)) +\
            r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) +\
                abs(possible_to_add)

            new_score = ",".join(
                [
                    str(question.category),
                    str(updated_score),
                    str(updated_possible), ""
                ])

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join(
                [
                    str(question.category),
                    str(score_to_add),
                    str(possible_to_add),
                    ""
                ])
            self.save()

    def show_exams(self):
        """
        Finds the previous quizzes marked as 'exam papers'.
        Returns a queryset of complete exams.
        """
        return Sitting.objects.filter(user=self.user, complete=True)

    def __str__(self):
        return self.user.username + ' - '  + self.score


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz):
        if quiz.random_order is True:
            question_set = quiz.question_set.all() \
                                            .select_subclasses() \
                                            .order_by('?')
        else:
            question_set = quiz.question_set.all() \
                                            .select_subclasses()

community/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from tagging.fields import TagField
from django.db.models import Q
import json
from random import randint
from django.db.models.signals import post_save
from notifications.signals import notify

class ApprovedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="approved")
    def search(self, query):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(body__icontains=query) |
                         Q(slug__icontains=query)
                         )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs
class PendingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="pending")

class Quest(models.Model):
    TYPE_CHOICES = (
        ('article', 'Article'),
        ('question', 'Question'),
        ('link', 'Link'),
    )

    STATUS_CHOICES = (
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('rejected', 'Rejected'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)
    asked_by = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='user', null=True,blank=True)
    body = models.TextField()
    date_asked = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='pending', blank=True,
                                     null=True)
    image_upload = models.ImageField(upload_to="QThumbnail", blank=True,
                                     null=True)
    tags = TagField()
    type = models.CharField(max_length=10,
                            choices=TYPE_CHOICES,
                            default='question')
    votes = models.ManyToManyField(User, related_name='vote_count',
                                   blank=True)

    class Meta:
        ordering = ('date_asked',)
        indexes = [models.Index(fields=[ 'date_asked', 'asked_by', 'title','tags'])]

    objects = models.Manager()  # The default manager.
    Approved = ApprovedManager()  # Our custom manager.
    Pending = PendingManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        """
        if self.status == "approved":
            message = "approved your question."
            notify.send(request.user ,recipient=self.asked_by, verb=message, url=self.get_absolute_url())
        """
        super(Quest, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('question_detail',
                       kwargs={'pk': self.pk, 'slug': self.slug})


class Answer(models.Model):
    question = models.ForeignKey(Quest,
                                 on_delete=models.CASCADE,
                                 related_name='answers')
    name = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='question_answered',blank=True, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    votes = models.ManyToManyField(User, blank=True)
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Answered by {} on {}'.format(self.name, self.Quest)


class Group(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(unique=True)
    group_thumb = models.ImageField(
        upload_to='group_thumbnail', blank=True, null=True)
    members = models.ManyToManyField(User, related_name='groups_joined',
                                     blank=True)
    questions = models.ManyToManyField(
        Quest, related_name='group_asked', blank=True)
    moderators = models.ManyToManyField(User, related_name='groups_heading',
                                        blank=True)
    rules = models.TextField()
    description = models.TextField()
    creator = models.ForeignKey(
        User, related_name='created_groups', on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('group_details',
        kwargs={'slug': self.slug})
    def save(self, *args,**kwargs):
        if Group.objects.filter(slug=slugify(self.name)).exists():
            extra = str(randint(1, 10000))
            self.slug = slugify(self.name) + "-" + extra
        else:
            self.slug = slugify(self.name)
        super(Group, self).save(*args, **kwargs)


class Interest(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, related_name="Interest",db_index=True)
    keytags = models.TextField(blank=True,null=True, db_index=True)

    def save(self, *args, **kwargs):
        self.keytags = json.dumps(self.keytags)
        super(Interest, self).save(*args, **kwargs)
    def get_user_interest(self):
        jsonDec = json.decoder.JSONDecoder()
        get_interests = jsonDec.decode(self.keytags)
        return get_interests

    def __str__(self):
        return self.user.username

class Visit(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, related_name= 'visits', db_index=True)
    questions = models.ManyToManyField(Quest, blank=True)
    def __str__(self):
        return self.user.username

templates/general/askquestion.html
{% extends 'layout.html' %}
{% block title %}
Ask your question
{% endblock %}
{% block content %}
<style>
  iframe.note-fullscreen {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw!important;
    height: 100vh!important;
    z-index: 4000;
  }
  </style>

<div class="w3-container w3-padding w3-white">

    <form method="POST" enctype="multipart/form-data" action="{% url 'ask_question' %}">
    {% csrf_token %}
      <p>
        <input type="text" class="w3-input" placeholder='suggest a catchy title for your question' name="title" id="id_title">
      </p>
      <p>
        <textarea name="body" cols="40" rows="10" id="id_body" hidden="true"></textarea>
        <script>
        var settings_id_body = {"width": "100%", "height": 480, "lang": "en-US", "toolbar": [["style", ["style"]], ["font", ["bold", "italic"]], ["para", ["ul", "ol", "paragraph"]], ["insert", ["link", "picture", "video"]]], "url": {"language": "/static/summernote/lang/summernote-en-US.min.js", "upload_attachment": "/summernote/upload_attachment/"}};
        </script>
        <div class="summernote-div"  cols="40" rows="10" width="100%" height="480">
          <iframe id="id_body_iframe" src="/summernote/editor/id_body/" frameborder="0" width="100%" height="480"></iframe>
        </div>      
      </p>

        <label for="id_image_upload">Thumbnail</label> 
        <input class="w3-input" type="file" name="image_upload" accept="image/*" id="id_image_upload">
      <p>  
        <input class="w3-input" type="text" name="tags" maxlength="255" id="id_tags" placeholder="Enter hashtags - seperated by a comma">
      </p>
      <p>
        <label for="id_type">Format as a/an</label> 
        <select class="w3-input" name="type" id="id_type">
          <option value="article">Article</option>
          <option value="question" selected>Question</option>
        </select>
      </p>      
    
      <input class="w3-button w3-blue w3-round-medium" type="submit" value="Ask">
    </form>
</div>


{% endblock %}

templates/general/category.html
{% extends "layout.html" %}
{% block title %}categories{% endblock %}


{% block content %}

<div class="w3-container">



<!-- fuoyenews category-->
{% if fnpost %}

 {% for post in fnpost %}

  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">
  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>

<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>

	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore
</button>
</p>
</div>

</div>
{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}


	{% endif %}





		{% if entpost %}

 {% for post in entpost %}
  <div class="w3-container w3-half">

<!--displaying post image-->
	<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">
  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>

	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
</div>

{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}

	{% endif %}




{% if spopost %}

 {% for post in spopost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>

	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
</div>
{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}

	{% endif %}




{% if hthpost %}
 {% for post in hthpost %}

  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>


	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
</div>
{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}

	{% endif %}


{% if tipost %}
 {% for post in tipost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
    </div>
    {% empty %}
    <div class="w3-red w3-container w3-opacity">
    <p>No Post In This Category</p>

    </div>

	{% endfor %}

	{% endif %}


<!-- Gossip category-->
{% if gospost %}
 {% for post in gospost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
        </div>
        {% empty %}
        <div class="w3-red w3-container w3-opacity">
        <p>No Post In This Category</p>

        </div>

	{% endfor %}
	{% endif %}


						<!-- entertainment category-->
{% if entpost %}
 {% for post in entpost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>

      </div>
      {% empty %}
      <div class="w3-red w3-container w3-opacity">
      <p>No Post In This Category</p>

      </div>

	{% endfor %}
		{% endif %}


			<!-- Health Category-->
{% if hthpost %}
 {% for post in hthpost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
</div>
{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}
	{% endif %}


		<!-- Tips Category-->
		{% if tipost %}
 {% for post in tipost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div></div>
{% empty %}
<div class="w3-red w3-container w3-opacity">
<p>No Post In This Category</p>

</div>

	{% endfor %}
		{% endif %}

		<!--Aspirant Category-->
		{% if fapost %}
 {% for post in fapost %}
  <div class="w3-container w3-half">
<!--displaying post image-->


<div class= " w3-display-container w3-image w3-hover-opacity w3-margin-top">

  <img src='{{post.image_upload.url}}'alt="Post Image" style="width:100%">
</div>
<!-- post content -->

    <div class="w3-container w3-white">
      <h1><b>{{post.title}}</b></h1>
      <p>{{post.author}}, <span class="w3-opacity">{{post.publish|date:"Y-m-d"}}</span></p>
    </div>
	<div class="w3-container w3-white">
      <div class="w3-container" >
        		<p>{{ post.body|truncatewords:20|linebreaks }}</p>
		</div>
		</div>

<!-- Readmore button-->

<div class="w3-container w3-white" >
<p>
<button name='readmore' onclick ="location.href='{{ post.get_absolute_url }}'" class=" w3-card w3-btn w3-round-xlarge w3-section w3-green w3-ripple">Readmore>>
</button>
</p>
</div>
</div>
{% empty %}
<div class="w3-red">
No Post In This Category

</div>

	{% endfor %}
		{% endif %}



</div>









{% endblock %}